on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 🔥 Clean old build files (prevents caching issues)
      - name: Clean old build files
        run: rm -rf node_modules/ dist/ build/

      # ✅ Install project dependencies
      - name: Install dependencies
        run: npm install  

      # ✅ Build project (Ensure output matches `firebase.json`)
      - name: Build project
        run: npm run build

      # ✅ Ensure the `dist/` folder exists (debugging)
      - name: Check build output
        run: ls -la dist || ls -la build

      # ✅ Deploy to Firebase Hosting with Debugging
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAUNCHFORCE_SCHOLARS }}
          channelId: live
          projectId: launchforce-scholars
        env:
          DEBUG: "true"
